handlebars src/public/js/pages/main/main.hbs -f src/public/js/pages/main/main.tmpl.js
handlebars src/public/js/pages/moviesList/moviesList.hbs -f src/public/js/pages/moviesList/moviesList.tmpl.js
handlebars src/public/js/pages/profile/profile.hbs -f src/public/js/pages/profile/profile.tmpl.js
handlebars src/public/js/pages/movie/movie.hbs -f src/public/js/pages/movie/movie.tmpl.js
handlebars src/public/js/pages/actor/actor.hbs -f src/public/js/pages/actor/actor.tmpl.js
handlebars src/public/js/pages/settings/settings.hbs -f src/public/js/pages/settings/settings.tmpl.js
handlebars src/public/js/pages/login/login.hbs -f src/public/js/pages/login/login.tmpl.js
handlebars src/public/js/pages/signup/signup.hbs -f src/public/js/pages/signup/signup.tmpl.js
handlebars src/public/js/pages/popup/popup.hbs -f src/public/js/pages/popup/popup.tmpl.js
handlebars src/public/js/pages/partials/navbar.hbs -f src/public/js/pages/partials/navbar.tmpl.js
handlebars src/public/js/pages/partials/loginIcons.hbs -f src/public/js/pages/partials/loginIcons.tmpl.js
