name: Simple Build

on:
  push:
    branches: [main, dev, similar]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Install sass
        run: npm install sass

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: 89.208.198.186
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/frontend/dist"
          strip_components: 1
